=== FA2021-K1/Buoy-ESP32-Firmware/JsonSchemes/SensorDump.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ferienakademie.de/SensorDump.schema.json",
    "title": "SensorDump",
    "description": "A dump of all sensor data from one buoy at one point in time",
    "type": "object",
    "properties": {
        "buoyID": {
            "description": "The unique identifier for the buoy",
            "type": "integer"
        },
        "date": {
            "description": "Timestamp when the measurements were taken; the format is ISO 8601 with 'T' as delimiter between date and time and +00 for timezone after seconds (as in the example)",
            "type": "string"
        },
        "location": {
            "description": "Current position of the buoy",
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "minimum": -90,
                    "maximum": 90
                },
                "longitude": {
                    "type": "number",
                    "minimum": -180,
                    "maximum": 180
                }          
            }
        },
        "measurements": {
            "description": "Array of all the measurements",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "sensorID": {
                        "description": "The unique ID of a sensor on a buoy",
                        "type": "integer"
                    },
                    "sensorType": {
                        "description": "The shared ID of the specific sensortype",
                        "type": "integer"
                    },
                    "measurement": {
                        "description": "The value retrieved from this sensor",
                        "type": "number"
                    }
                }
            }
        }
    }
}

=== FA2021-K1/Buoy-ESP32-Firmware/JsonSchemes/SensorDump.example.json
[{
	"buoyID":0,
	"date":"2021-09-26T11:09:00+00",
	"location":{"latitude":46.741,"longitude":11.441},
	"measurements":[
		{"sensorID":2,"sensorType":2,"measurement":4.14},
		{"sensorID":1,"sensorType":1,"measurement":5.14}
	]
},
{
    "buoyID":1,
    "date":"2021-09-26T11:09:00+00",
    "location":{"latitude":46.743,"longitude":11.445},
    "measurements":[
        {"sensorID":1,"sensorType":2,"measurement":4.15},
        {"sensorID":2,"sensorType":1,"measurement":5.15}
    ]
}]
